name: musicplayer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  permission_handler: ^11.1.0
  path_provider: ^2.1.2
  flutter_media_metadata: ^1.0.0+1
  sqflite: ^2.3.0
  avatar_glow: ^3.0.1
  marquee_text: ^2.5.0+1
  just_audio: ^0.9.36
  flutter_audio_waveforms: ^1.2.1+8
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

